/*
 * Main.java
 *
 * Created on December 22, 2004, 9:36 AM
 */

/**
 *
 * @author  Illya Kysil
 */
public class Main extends javax.swing.JFrame {
  
  /** Creates new form Main */
  public Main() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    info.clearthought.layout.TableLayout _tableLayoutInstance;
    info.clearthought.layout.TableLayout _tableLayoutInstance1;
    
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jList1 = new javax.swing.JList();
    jButton4 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    
    _tableLayoutInstance1 = new info.clearthought.layout.TableLayout();
    _tableLayoutInstance1.setHGap(0);
    _tableLayoutInstance1.setVGap(0);
    _tableLayoutInstance1.setColumn(new double[]{78,info.clearthought.layout.TableLayout.PREFERRED,5,info.clearthought.layout.TableLayout.PREFERRED,5,info.clearthought.layout.TableLayout.PREFERRED,5,info.clearthought.layout.TableLayout.PREFERRED,5,0,info.clearthought.layout.TableLayout.PREFERRED});
    _tableLayoutInstance1.setRow(new double[]{5,13,12,13,13});
    getContentPane().setLayout(_tableLayoutInstance1);
    
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });
    
    jButton2.setText("jButton2");
    getContentPane().add(jButton2, new info.clearthought.layout.TableLayoutConstraints(1, 2, 1, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    jButton3.setText("jButton3");
    getContentPane().add(jButton3, new info.clearthought.layout.TableLayoutConstraints(3, 2, 3, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    jList1.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "1", "2", "3" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jList1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
    getContentPane().add(jList1, new info.clearthought.layout.TableLayoutConstraints(5, 1, 5, 4, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    jButton4.setText("jButton4");
    getContentPane().add(jButton4, new info.clearthought.layout.TableLayoutConstraints(7, 2, 7, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    _tableLayoutInstance = new info.clearthought.layout.TableLayout();
    _tableLayoutInstance.setHGap(0);
    _tableLayoutInstance.setVGap(0);
    _tableLayoutInstance.setColumn(new double[]{});
    _tableLayoutInstance.setRow(new double[]{});
    jPanel1.setLayout(_tableLayoutInstance);
    
    getContentPane().add(jPanel1, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    jButton1.setText("jButton1");
    getContentPane().add(jButton1, new info.clearthought.layout.TableLayoutConstraints(10, 2, 10, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    
    pack();
  }//GEN-END:initComponents
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit(0);
  }//GEN-LAST:event_exitForm
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new Main().show();
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JList jList1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
  
}
